# unless otherwise specified, hooks run on push only
default_stages: [push]
repos:
  # formatters and linters are available in the virtualenv so they can be run from the makefile & vscode
  - repo: local
    hooks:
      - id: ruff
        name: ruff
        entry: .venv/bin/ruff check --force-exclude
        language: system
        types: [python]
        require_serial: true
#      - id: ruff-format
#        name: ruff-format
#        entry: .venv/bin/ruff format
#        language: system
#        types: [python]
#        require_serial: true
      - id: pyright
        name: pyright
        entry: node_modules/.bin/pyright
        # run on all files to catch type errors that affect unchanged files
        pass_filenames: false
        language: system
        types: [python]
#      - id: test
#        name: test
#        entry: make test
#        # run on all files
#        pass_filenames: false
#        language: system
#        types: [python]
